# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_weather_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='tmax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='tmin',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
